### ISSUE TITLE
Wrong Configuration settings in python-2.8/1B

### ISSUE THREAD

**Issue by 4IK1d** [YuchuanTian/DiJiang#3]
Seems we got wrong directory name or wrong settings in `config.json`

`config.json` under `modeling/pythia-2.8B`
<img width="912" alt="image" src="https://github.com/YuchuanTian/DiJiang/assets/96651850/0d39c33e-8cf4-414d-9bce-676c8fcf1f34">

`config.json` under `modeling/pythia-1B`
<img width="557" alt="image" src="https://github.com/YuchuanTian/DiJiang/assets/96651850/56a51eb8-3bf2-46ec-9b83-f7783eef9935">

Original `config.json` with pythia-2.8B
<img width="562" alt="image" src="https://github.com/YuchuanTian/DiJiang/assets/96651850/1f4037b7-ac50-4473-aa76-5cfd5f36c58a">

**Comment by YuchuanTian** [comment]
Thanks for your kind reminder. I have corrected this mistake.
